version: '3.9'
services:
  customer-app:
    image: customer-ms
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - mysqldb
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: mysqldb
  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_PASSWORD: sqlroot1
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql

   # volumes:
     #    - ./sql/create_transferapp_db.sql:/docker-entrypoint-initdb.d/create_transferapp_db.sql

#  rabbitmq:
#    image: rabbitmq
#    container_name: 'rabbitmq'
#    ports:
#      - 5672:5672
#      - 15672:15672
